### ISSUE TITLE
BeS Contributor's Guide must have information on playbook Type and Playbook Naming convention to be followed

### ISSUE THREAD

**Issue by panickervinod** [Be-Secure/besecure-playbooks-store#21]
BeS Contributor's Guide must have information on playbook Type and Naming convention to be followed , this link must be made available in the Readme.md for the CE repo.

Given examples of different types of playbooks in the Readme.md i.e for *.sh, *.yaml (Automated) , Jupyter Note books (Interactive) , and *.md markdown ( Manual) .

**Comment by harimohanr** [comment]
Addressed this in #23 #24
